version: '3'
services:
  server1:
    restart: unless-stopped
    build:
      context: ./backend
    container_name: node-server1

  server2:
    restart: unless-stopped
    build:
      context: ./backend
    container_name: node-server2

  server3:
    restart: unless-stopped
    build:
      context: ./backend
    container_name: node-server3

  client:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: react-frontend
    stdin_open: true
    # volumes:
    #   - ./frontend:/srv/app/nm-client
    #   - /srv/app/nm-client/node_modules

  proxy:
    # image: nginx:1.17
    restart: unless-stopped
    build:
      context: ./nginx
    ports:
      - "8080:8080"
    container_name: nginx
    
    # volumes: 
    #   - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
